modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
issueTrackerURL = "https://github.com/jmils/BouncyBalls/issues"
[[mods]] #mandatory
modId = "bouncyballs" #mandatory
version = "${version}" #mandatory
displayName = "BouncyBalls" #mandatory
displayTest = "MATCH_VERSION"
description = '''

'''
[[dependencies.bouncyballs]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.bouncyballs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.4)"
ordering = "NONE"
side = "BOTH"
[[dependencies.bouncyballs]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
